sudo: required
dist: trusty
language: generic
cache:
- apt
notifications:
  email: false
  slack:
    secure: cgBnoOCw46e5/JRi4s7tgaXK3klSERRclRF9J3BFYtHxZ8drKu/or+9jQYrfyb+I9TzWGUxrWuF6Nfq8n2bJehaGvr+s64ygVyUxfP1s6jVC4PzyUIk4+DrUfWR4S/yTZlO0R2Udf3emKCm3YZVN4C5QVClRzzBZw5a/VEXpsHWnzeJacB2wXWsjtwd+kIoRWaw6OlTBoF+J6ZtZirG2QxOBdSzpRvPpQwhftr/k6Q50gZ76R+TOF9HIcMnpLncTiry3UX9y1qljGTpQsAC1SHlEFIwrq0qjYvBI/AATHf1i7YCFYu2vEs7CS3+H1jNb+7yF5Tq1ZSgznwVS8FELfdy20XNbhcFFzcK7kWY2+EU+DHYAMdv7I6FcNW4ZRiFuaNiOsDJYjARlHYbcq0c9h0vFw/cGyuXQRZe4mpNxuf6B4xjEN55IykiZ1MTac8IfjvGgp+YkcaJnMZyaBH7XTgaTgqK90+sMSl8ekOWhR1/eF2u6EZyuK/uQh/1UR8uXAM58kAiyiFvZoL0xcATFhxA19OI1GhV8Ys47ndeAJRzXc64XUmXyrzTHHCrr5wh1EBU4UvpvZaG8gVH6DYdBc/XQtfdiNJ/WoWS5wzxmJT4WACwFAtAZL8Z2zOuCowvUIVQivPXrZ2XIXq8WM+Q/WkwYu5eFW7xDrPiDbFnO03k=
addons:
  apt:
    packages:
    - valgrind
    - libeigen3-dev

# Configuration variables. All variables are global now, but this can be used to
# trigger a build matrix for different ROS distributions if desired.
env:
  global:
  - CI_SOURCE_PATH=$(pwd)
  - REPO_NAME=$(echo $TRAVIS_REPO_SLUG | cut -d"/" -f2)
  - CTEST_EXT_COLOR_OUTPUT=TRUE
  - CTEST_BUILD_FLAGS=-j8
matrix:
  include:
  - os: linux
    compiler: g++-4.9
    env: CTEST_TARGET_SYSTEM=Linux-gcc CTEST_MODEL=Nightly CXX=g++-4.9 CC=gcc-4.9
    addons:
      apt:
        packages:
        - g++-4.9
        sources: &1
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty
        - llvm-toolchain-trusty-3.7
        - llvm-toolchain-trusty-3.6
  - os: linux
    compiler: clang-3.6
    env: CTEST_TARGET_SYSTEM=Linux-gcc CTEST_MODEL=Nightly CXX=clang++-3.6 CC=clang-3.6
    addons:
      apt:
        packages:
        - clang-3.6
    sources: *1
  # - os: osx
  #   compiler: clang
  #   env: CTEST_TARGET_SYSTEM=MacOS-clang  CTEST_MODEL=Nightly


install:
- cd $CI_SOURCE_PATH
- mkdir build
- cd build
- cmake ../
- make -j8
script:
- cd $CI_SOURCE_PATH/build/test
- ctest -W -S
